//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomMvc.Foundation.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Field> Fields { get; set; }
        public virtual DbSet<ItemRendering> ItemRenderings { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<Layout> Layouts { get; set; }
        public virtual DbSet<Link> Links { get; set; }
        public virtual DbSet<Presentation> Presentations { get; set; }
        public virtual DbSet<Property> Properties { get; set; }
        public virtual DbSet<Rendering> Renderings { get; set; }
        public virtual DbSet<Template> Templates { get; set; }
    }
}
